export enum Region {
    BRATISLAVSKY = 'BRATISLAVSKY',
    TRNAVSKY = 'TRNAVSKY',
    TRENČIANSKY = 'TRENČIANSKY',
    NITRIANSKY = 'NITRIANSKY',
    ZILINSKY = 'ZILINSKY',
    BANSKOBYSTRICKY = 'BANSKOBYSTRICKY',
    PRESOVSKY = 'PRESOVSKY',
    KOSICKY = 'KOSICKY'
}
